source 'https://rubygems.org'
# gem 'simple_form', '~> 3.5'

gem 'bootstrap-sass', '~> 3.3.7'
gem 'sass-rails', '>= 3.2'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'devise', '~> 4.4', '>= 4.4.1'
gem 'rb-readline'
gem 'paperclip', '~> 5.2', '>= 5.2.1'
gem 'sqlite3'
gem 'simple_form'
gem 'puma', '~> 3.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'

gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.5'

group :development, :test do

  gem 'byebug', platform: :mri
end

group :development do

  gem 'web-console'
  gem 'listen', '~> 3.0.5'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
